In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

/Users/daniel/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [5]:
df_2007 = pd.read_csv('2007-2011.csv', header=1)

/Users/daniel/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
df_2007.describe().T

,count,mean,std,min,25%,50%,75%,max
member_id,42535,825702.551170,279540.905635,70473.00,638479.500000,824178.00,1033946.500000,1314167.000000
loan_amnt,42535,11089.722581,7410.938391,500.00,5200.000000,9700.00,15000.000000,35000.000000
funded_amnt,42535,10821.585753,7146.914675,500.00,5000.000000,9600.00,15000.000000,35000.000000
funded_amnt_inv,42535,10139.830603,7131.686446,0.00,4950.000000,8500.00,14000.000000,35000.000000
installment,42535,322.623063,208.927216,15.67,165.520000,277.69,428.180000,1305.190000
annual_inc,42531,69136.556420,64096.349719,1896.00,40000.000000,59000.00,82500.000000,6000000.000000
dti,42535,13.373043,6.726315,0.00,8.200000,13.47,18.680000,29.990000
delinq_2yrs,42506,0.152449,0.512406,0.00,0.000000,0.00,0.000000,13.000000
fico_range_low,42535,713.052545,36.188439,610.00,685.000000,710.00,740.000000,825.000000
fico_range_high,42535,717.052545,36.188439,614.00,689.000000,714.00,744.000000,829.000000
inq_last_6mths,42506,1.081424,1.527455,0.00,0.000000,1.00,2.000000,33.000000
mths_since_last_delinq,15609,35.017618,22.418427,0.00,17.000000,33.00,51.000000,120.000000
mths_since_last_record,3651,59.175568,47.145396,0.00,0.000000,85.00,101.000000,129.000000
open_acc,42506,9.343951,4.496274,1.00,6.000000,9.00,12.000000,47.000000
pub_rec,42506,0.058156,0.245713,0.00,0.000000,0.00,0.000000,5.000000
revol_bal,42535,14297.860915,22018.441010,0.00,3635.000000,8821.00,17251.000000,1207359.000000
total_acc,42506,22.124406,11.592811,1.00,13.000000,20.00,29.000000,90.000000
out_prncp,42535,65.003480,452.472144,0.00,0.000000,0.00,0.000000,10418.060000
out_prncp_inv,42535,64.684346,450.772792,0.00,0.000000,0.00,0.000000,10410.560000
total_pymnt,42535,11951.421711,8967.283744,0.00,5458.963394,9670.66,16347.935053,57835.279911
total_pymnt_inv,42535,11244.663743,8907.940554,0.00,4789.110000,8945.16,15464.695000,57628.730000
total_rec_prncp,42535,9613.917951,7019.286957,0.00,4400.000000,8000.00,13200.000000,35000.020000
total_rec_int,42535,2236.719059,2574.943073,0.00,657.100000,1339.14,2802.700000,23388.230000
total_rec_late_fee,42535,1.505498,7.781707,0.00,0.000000,0.00,0.000000,209.000000
recoveries,42535,99.279293,712.380559,0.00,0.000000,0.00,0.000000,29623.350000
collection_recovery_fee,42535,13.771540,158.625616,0.00,0.000000,0.00,0.000000,7002.190000
last_pymnt_amnt,42535,2607.976717,4385.953769,0.00,211.750000,524.59,3151.695000,36115.200000
last_fico_range_high,42535,685.868367,84.418817,0.00,639.000000,699.00,744.000000,850.000000
last_fico_range_low,42535,665.438698,145.356288,0.00,635.000000,695.00,740.000000,845.000000
collections_12_mths_ex_med,42390,0.000000,0.000000,0.00,0.000000,0.00,0.000000,0.000000
...,...,...,...,...,...,...,...,...
mo_sin_old_rev_tl_op,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mo_sin_rcnt_rev_tl_op,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mo_sin_rcnt_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mort_acc,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mths_since_recent_bc,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mths_since_recent_bc_dlq,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mths_since_recent_inq,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mths_since_recent_revol_delinq,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_accts_ever_120_pd,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_actv_bc_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_actv_rev_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_bc_sats,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_bc_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_il_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_op_rev_tl,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_rev_accts,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_rev_tl_bal_gt_0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_sats,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_tl_120dpd_2m,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_tl_30dpd,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_tl_90g_dpd_24m,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
num_tl_op_past_12m,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pct_tl_nvr_dlq,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
percent_bc_gt_75,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pub_rec_bankruptcies,41170,0.045227,0.208737,0.00,0.000000,0.00,0.000000,2.000000
tax_liens,42430,0.000024,0.004855,0.00,0.000000,0.00,0.000000,1.000000
tot_hi_cred_lim,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_bal_ex_mort,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_bc_limit,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_il_high_credit_limit,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN