In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Import 2014 Data

In [2]:
df = pd.read_csv('../data/LoanStats2014.csv', header=1, skip_footer=2)

C:\Users\Daniel\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skip_footer; you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,235629,21819773.996248,8459394.329580,57167.00,13847942.00,20689310.00,29243893.00,38098114.000000
member_id,235629,24019299.796719,8825162.024128,137225.00,15579724.00,22953173.00,31767065.00,40860827.000000
loan_amnt,235629,14870.156793,8438.318193,1000.00,8325.00,13000.00,20000.00,35000.000000
funded_amnt,235629,14870.156793,8438.318193,1000.00,8325.00,13000.00,20000.00,35000.000000
funded_amnt_inv,235629,14865.334169,8435.524995,950.00,8325.00,13000.00,20000.00,35000.000000
installment,235629,442.472125,245.046730,23.36,265.68,384.11,578.69,1409.990000
annual_inc,235629,74854.148281,55547.533374,3000.00,45377.00,65000.00,90000.00,7500000.000000
dti,235629,18.040770,8.023002,0.00,12.02,17.63,23.76,39.990000
delinq_2yrs,235629,0.344512,0.898319,0.00,0.00,0.00,0.00,22.000000
inq_last_6mths,235629,0.755760,1.033981,0.00,0.00,0.00,1.00,6.000000
mths_since_last_delinq,119748,33.398019,21.779818,0.00,15.00,30.00,49.00,188.000000
mths_since_last_record,41524,70.711444,28.463384,0.00,50.00,69.00,97.00,121.000000
open_acc,235629,11.668093,5.268175,0.00,8.00,11.00,14.00,84.000000
pub_rec,235629,0.222460,0.604696,0.00,0.00,0.00,0.00,63.000000
revol_bal,235629,16508.089289,21462.890835,0.00,6336.00,11686.00,20528.00,2560703.000000
total_acc,235629,26.010826,11.895675,2.00,17.00,24.00,33.00,156.000000
out_prncp,235629,3327.455964,5260.724113,0.00,0.00,0.00,4604.18,30971.490000
out_prncp_inv,235629,3326.560153,5259.447268,0.00,0.00,0.00,4604.18,30971.490000
total_pymnt,235629,13240.805156,8502.959947,0.00,7040.46,11223.43,17460.13,55522.420031
total_pymnt_inv,235629,13236.339415,8499.721770,0.00,7037.68,11220.45,17453.60,55522.420000
total_rec_prncp,235629,10201.450896,7365.053171,0.00,4950.00,8126.22,13525.00,35000.000000
total_rec_int,235629,2899.380493,2635.148852,0.00,1061.16,2040.13,3878.58,21347.780000
total_rec_late_fee,235629,0.784354,6.325232,0.00,0.00,0.00,0.00,338.460000
recoveries,235629,139.189411,677.977685,0.00,0.00,0.00,0.00,24286.130000
collection_recovery_fee,235629,21.511342,113.142954,0.00,0.00,0.00,0.00,4371.487200
last_pymnt_amnt,235629,3738.874127,6062.279448,0.00,330.57,611.82,4955.93,36234.440000
collections_12_mths_ex_med,235629,0.015440,0.143081,0.00,0.00,0.00,0.00,20.000000
mths_since_last_major_derog,66478,43.370378,21.961926,0.00,26.00,43.00,60.00,188.000000
policy_code,235629,1.000000,0.000000,1.00,1.00,1.00,1.00,1.000000
annual_inc_joint,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
mo_sin_old_rev_tl_op,235629,185.748609,93.040778,3.00,120.00,168.00,234.00,842.000000
mo_sin_rcnt_rev_tl_op,235629,13.070407,16.111818,0.00,4.00,8.00,16.00,372.000000
mo_sin_rcnt_tl,235629,7.997186,8.738951,0.00,3.00,6.00,10.00,226.000000
mort_acc,235629,1.851173,2.161213,0.00,0.00,1.00,3.00,37.000000
mths_since_recent_bc,233383,24.444917,30.295965,0.00,6.00,14.00,30.00,616.000000
mths_since_recent_bc_dlq,62281,39.630915,22.573247,0.00,20.00,39.00,58.00,170.000000
mths_since_recent_inq,213937,6.920481,5.931004,0.00,2.00,5.00,10.00,25.000000
mths_since_recent_revol_delinq,84766,35.458580,22.298694,0.00,16.00,32.00,52.00,180.000000
num_accts_ever_120_pd,235629,0.503414,1.264196,0.00,0.00,0.00,0.00,33.000000
num_actv_bc_tl,235629,3.687445,2.155902,0.00,2.00,3.00,5.00,26.000000
num_actv_rev_tl,235629,5.804888,3.141478,0.00,4.00,5.00,7.00,38.000000
num_bc_sats,235629,4.647730,2.724450,0.00,3.00,4.00,6.00,35.000000
num_bc_tl,235629,8.544008,4.821962,0.00,5.00,8.00,11.00,61.000000
num_il_tl,235629,8.572918,7.302646,0.00,4.00,7.00,11.00,150.000000
num_op_rev_tl,235629,8.276592,4.318805,0.00,5.00,7.00,10.00,62.000000
num_rev_accts,235629,15.298643,8.055087,2.00,9.00,14.00,20.00,105.000000
num_rev_tl_bal_gt_0,235629,5.769557,3.123751,0.00,4.00,5.00,7.00,38.000000
num_sats,235629,11.618825,5.266031,0.00,8.00,11.00,14.00,84.000000
num_tl_120dpd_2m,227769,0.000966,0.032038,0.00,0.00,0.00,0.00,2.000000
num_tl_30dpd,235629,0.003722,0.065202,0.00,0.00,0.00,0.00,4.000000
num_tl_90g_dpd_24m,235629,0.094581,0.490951,0.00,0.00,0.00,0.00,22.000000
num_tl_op_past_12m,235629,2.006892,1.604793,0.00,1.00,2.00,3.00,26.000000
pct_tl_nvr_dlq,235629,94.239886,8.463073,16.70,91.40,97.60,100.00,100.000000
percent_bc_gt_75,233072,50.770059,34.915657,0.00,22.20,50.00,80.00,100.000000
pub_rec_bankruptcies,235629,0.134873,0.376381,0.00,0.00,0.00,0.00,12.000000
tax_liens,235629,0.055757,0.409256,0.00,0.00,0.00,0.00,63.000000
tot_hi_cred_lim,235629,170248.976930,171996.125636,0.00,47800.00,111514.00,247522.00,9999999.000000
total_bal_ex_mort,235629,48389.432888,45966.066095,0.00,20769.00,36685.00,60821.00,2688920.000000
total_bc_limit,235629,20031.414966,20209.993827,0.00,7000.00,13800.00,26200.00,1090700.000000
total_il_high_credit_limit,235629,39883.390920,41431.705786,0.00,13592.00,30000.00,53566.00,1241783.000000

In [8]:
#printout of all feature names
for i in df.columns:
    print i

id
member_id
loan_amnt
funded_amnt
funded_amnt_inv
term
int_rate
installment
grade
sub_grade
emp_title
emp_length
home_ownership
annual_inc
verification_status
issue_d
loan_status
pymnt_plan
url
desc
purpose
title
zip_code
addr_state
dti
delinq_2yrs
earliest_cr_line
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
revol_util
total_acc
initial_list_status
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_d
last_pymnt_amnt
next_pymnt_d
last_credit_pull_d
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
application_type
annual_inc_joint
dti_joint
verification_status_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_il_6m
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats
num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit

In [9]:
df[['total_pymnt', 'total_pymnt_inv', 'total_rec_int', 'total_rec_late_fee', 'total_rec_prncp']]

,total_pymnt,total_pymnt_inv,total_rec_int,total_rec_late_fee,total_rec_prncp
0,6090.420000,6090.42,872.67,0,5217.75
1,17392.370000,17392.37,2392.37,0,15000.00
2,9973.430000,9973.43,373.43,0,9600.00
3,2281.980000,2281.98,339.61,0,704.38
4,7059.630000,7059.63,3566.63,0,3493.00
5,25512.200000,25512.20,4087.20,0,21425.00
6,19562.310001,19562.31,2562.31,0,17000.00
7,13907.790000,13907.79,3061.64,0,7301.23
8,2622.220000,2622.22,122.22,0,2500.00
9,5746.890000,5746.89,1603.20,0,2628.14
10,5431.680000,5431.68,181.68,0,5250.00
11,18586.720000,18586.72,2586.72,0,16000.00
12,6957.450000,6957.45,1562.16,0,5395.29
13,12738.530000,12738.53,7492.73,0,5245.80
14,2375.950000,2375.95,375.95,0,2000.00
15,5481.040000,5481.04,795.27,0,4685.77
16,2140.630000,2140.63,419.91,0,1720.72
17,2101.520000,2101.52,101.52,0,2000.00
18,3084.540000,3084.54,871.38,0,2213.16
19,30628.650000,30628.65,2628.65,0,28000.00
20,1575.200000,1575.20,397.39,0,1177.81
21,2059.850000,2059.85,59.85,0,2000.00
22,9382.110000,9382.11,5068.80,0,4313.31
23,9988.940000,9988.94,1959.62,0,8029.32
24,9387.620000,9387.62,2084.22,0,5481.70
25,5278.390000,5278.39,1198.14,0,4080.25
26,3575.850000,3575.85,708.23,0,2867.62
27,13371.180000,13371.18,2893.11,0,10478.07
28,1139.770000,1139.77,139.77,0,1000.00
29,7595.780000,7595.78,1362.83,0,6232.95
...,...,...,...,...,...
235599,43086.989997,43086.99,8086.99,0,35000.00
235600,5347.200000,5347.20,1910.39,0,3436.71
235601,15178.050000,15178.05,2378.05,0,12800.00
235602,21379.480005,21349.79,3379.48,0,18000.00
235603,30944.420000,30944.42,8716.81,0,22227.61
235604,7642.860000,7642.86,1086.95,0,6555.91
235605,16463.489995,16434.91,2063.49,0,14400.00
235606,16935.900001,16935.90,2935.90,0,14000.00
235607,28874.990024,28874.99,4874.99,0,24000.00
235608,15905.521364,15905.52,655.52,0,15250.00
235609,34606.390000,34579.35,2606.39,0,32000.00
235610,12954.800000,12954.80,1708.86,0,11245.94
235611,11431.310000,11431.31,2093.11,0,9338.20
235612,15181.529999,15181.53,3181.53,0,12000.00
235613,11235.720000,11235.72,1235.72,0,10000.00
235614,12673.800000,12649.89,7008.16,0,5665.64
235615,6527.140000,6527.14,1900.82,0,4626.32
235616,6865.440002,6865.44,865.44,0,6000.00
235617,11148.260000,11148.26,5917.12,0,5231.14
235618,11773.940000,11773.94,1773.94,0,10000.00
235619,6865.573895,6865.57,865.57,0,6000.00
235620,2030.000000,2030.00,510.45,0,360.08
235621,5632.300000,5624.48,1050.78,0,4580.89
235622,12394.270000,12394.27,2394.27,0,10000.00
235623,17314.500000,17314.50,3315.90,0,13998.60
235624,14764.800000,14764.80,5971.12,0,8793.68
235625,4680.000000,4680.00,2840.88,0,1837.04
235626,2126.579838,2126.58,126.58,0,2000.00
235627,17487.380000,17487.38,7909.89,0,9577.49
235628,12497.420000,12466.18,3215.11,0,9282.31

In [10]:
df['total_pymnt'] = df['total_pymnt'].apply(lambda x: round(x, 2))

In [12]:
sum(df['total_pymnt']==df['total_pymnt_inv'])

218376